spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: "zc142500"
          url: jdbc:mysql://localhost:3306/person?characterEncoding=utf8&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.jdbc.Driver
        #  schema: db/schema.sql
    #    slave_1:
    #      username: root
    #      password: "zc142500"
    #      url: jdbc:mysql://192.168.31.xx:3306/dynamic
    #      driver-class-name: com.mysql.jdbc.Driver
    #    slave_2:
    #      username: root
    #      password: "zc142500"
    #      url: jdbc:mysql://192.168.31.xx:3306/dynamic
    #      driver-class-name: com.mysql.jdbc.Driver
    #    slave_3:
    #      username: root
    #      password: "zc142500"
    #      url: jdbc:mysql://192.168.31.xx:3306/dynamic
    #      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: ito-person-core-provider
#  redis:
#    database: 0
#    timeout: 60000
#    lettuce:
#      pool:
#        max-active: 100
#        max-idle: 50
#        min-idle: 10
#        max-wait: 1000
#    sentinel:
#      master: mymaster
#      nodes: 172.19.0.2:16379,172.19.0.4:16380,172.19.0.3:16381
logging:
  level:
    com.baomidou: debug
server:
  port: 18899

