spring:
  application:
    name: ito-person-cache-provider
  redis:
    database: 0
    timeout: 60000
    lettuce:
      pool:
        max-active: 100
        max-idle: 50
        min-idle: 10
        max-wait: 1000
    sentinel:
      master: mymaster
      nodes: 172.20.0.3:16379,172.20.0.4:16380,172.20.0.2:16381
logging:
  level:
    com.baomidou: debug
server:
  port: 18900

